//
//  ReviewRelicInteractorTests.swift
//  ReviewRelic
//
//  Created by Raheel Sadiq on 27/03/2021.
//  Copyright (c) 2021 CocoaPods. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import ReviewRelic
import XCTest

class ReviewRelicInteractorTests: XCTestCase
{
    // MARK: Subject under test
    
    var sut: ReviewRelicInteractor!
    
    // MARK: Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        setupReviewRelicInteractor()
    }
    
    override func tearDown()
    {
        super.tearDown()
    }
    
    // MARK: Test setup
    
    func setupReviewRelicInteractor()
    {
        sut = ReviewRelicInteractor()
    }
    
    // MARK: Test doubles
    
    class ReviewRelicPresentationLogicSpy: ReviewRelicPresentationLogic {
        var dataPresentedCalled = false
        func presentData(response: ReviewRelicModels.Response){
            dataPresentedCalled = true
        }
        
        var failurePresentedCalled = false
        func presentDataFailure(){
            failurePresentedCalled = true
        }
    }
    
    // MARK: Tests
    
    func testRequestReviewDataSuccess() {
        
        let spy = ReviewRelicPresentationLogicSpy()
        sut.presenter = spy
        sut.requestReviewData()
        
        XCTAssertTrue(spy.dataPresentedCalled, "Data not presented")
    }
    
    func testRequestReviewDataFailure() {
        
        let spy = ReviewRelicPresentationLogicSpy()
        sut.presenter = spy
        sut.requestReviewData()
        
        XCTAssertTrue(spy.dataPresentedCalled, "Failure not presented")
    }
}
